import Head from "next/head";
import Layout from "./components/Layout";
import LandingPage from "./LandingPage";
import Loginn from "./Login";
import { useState } from "react";

export default function Home() {
  const adminUser = { username: "donny", password: "donny123" };

  const [user, setUser] = useState({ username: "" });
  const [error, setError] = useState();

  const Login = (details) => {
    if (
      details.username === adminUser.username &&
      details.password === adminUser.password
    ) {
      console.log(details);
      console.log("Login");
      setUser({
        username: details.username,
      });
    } else {
      console.log(details);
      console.log("Data salah");
    }
  };

  const Logout = () => {
    setUser({ username: "" });
    console.log("Logout");
  };

  return (
    <div>
      <Head>
        <title>Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.ico" />
      </Head>

      {user.username !== "" ? <LandingPage /> : <Loginn Login={Login} />}
    </div>
  );
}
