import Head from "next/head";
import Layout from "./components/Layout";

export default function LandingPage() {
  return (
    <div>
      <Layout />
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.ico" />
      </Head>

      <div className="article">
        <h1>Welcome Admin</h1>
      </div>
    </div>
  );
}
